name = "TestFilter"
uuid = "3e94a9e4-814b-4e46-b2d7-6712821a4d22"
authors = ["Viktor G. Gumennyy <20798349+sairus7@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
